cask_args appdir: '/Applications'

tap 'homebrew/core'
tap 'homebrew/cask'
tap 'homebrew/bundle'
tap 'homebrew/cask-fonts'
tap 'homebrew/services'
tap 'caskroom/cask'
tap 'caskroom/versions'
tap 'neovim/neovim'
tap 'universal-ctags/universal-ctags'

# Binaries
brew 'ack'
brew 'ansible'
brew 'awscli'
brew 'autoenv'
brew 'autoconf'
brew 'automake'
brew 'bash'
brew 'bash-completion2'
brew 'cask'
brew 'coreutils'
brew 'cmake'
brew 'ctags'
brew 'direnv'
brew 'editorconfig'
brew 'findutils'
brew 'fzf'
brew 'gnu-sed', args: ['with-default-names']
brew 'goenv'
brew 'gpg'
brew 'grv'
brew 'git'
brew 'git-flow-avh'
brew 'grep'
brew 'howdoi'
brew 'htop'
brew 'httpie'
brew 'hugo'
brew 'iftop'
brew 'jq'
brew 'kubernetes-helm'
brew 'nmap'
brew 'neovim'
brew 'make'
brew 'mas'
brew 'moreutils'
brew 'pyenv'
brew 'pyenv-virtualenv'
brew 'rsync'
brew 'readline'
brew 'reattach-to-user-namespace'
brew 'telnet'
brew 'terraform'
brew 'translate-shell'
brew 'tree'
brew 'tmux'
brew 'universal-ctags/universal-ctags/universal-ctags', args: ['HEAD', 'without-doc']
brew 'wrk'
brew 'zsh'
brew 'zsh-completions'

# Apps
cask 'alfred'
cask 'appcleaner'
cask 'clipy'
cask 'docker-edge'
cask 'google-chrome'
cask 'iterm2'
cask 'java' unless system '/usr/libexec/java_home --failfast'
cask 'macdown'
cask 'ngrok'
cask 'notion'
cask 'minikube'
cask 'sequel-pro'
cask 'slack'
cask 'transmission'
cask 'tunnelblick'
cask 'virtualbox'
cask 'visual-studio-code'

# Fonts
# Ref: https://github.com/Homebrew/homebrew-cask-fonts/tree/master/Casks
cask 'font-fantasquesansmono-nerd-font'

# Mac App Store
mas 'Agenda', id: 1287445660
mas 'The Unarchiver', id: 425424353
mas 'myTuner Radio', id: 881415018
mas 'Xcode', id: 497799835
