#!/usr/bin/env bash

# Ref: https://github.com/zchee/deoplete-jedi/wiki/Setting-up-Python-for-Neovim
# pyenv virtualenv $PY2_VER neovim2
# pyenv virtualenv $PY3_VER neovim3

# pyenv activate neovim2
# pip install neovim
# pyenv which python  # Note the path

# pyenv activate neovim3
# pip install neovim
# pyenv which python  # Note the path

# pip install flake8
# ln -s `pyenv which flake8` ~/bin/flake8  # Assumes that $HOME/bin is in $PATH

cd "$(dirname "${BASH_SOURCE}")";

mkdir -p ~/.config/nvim

curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

rsync ./init.vim ~/.config/nvim/init.vim;