#!/usr/bin/env bash

# Ref: https://github.com/zchee/deoplete-jedi/wiki/Setting-up-Python-for-Neovim

#pyenv virtualenv ${PY2_VER:-2.7.15} neovim2
#pyenv virtualenv ${PY3_VER:-3.7.1} neovim3

#pyenv activate neovim2
#pip install neovim

#pyenv activate neovim3
#pip install neovim

#pip install flake8
#ln -s `pyenv which flake8` ~/bin/flake8  # Assumes that $HOME/bin is in $PATH

cd "$(dirname "${BASH_SOURCE}")";

mkdir -p ~/.config/nvim

if [ ! -f  ~/.local/share/nvim/site/autoload/plug.vim  ]; then
	curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
			https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

rsync init.vim ~/.config/nvim/init.vim;

# Install nvim plugins
nvim +PlugInstall +qall > /dev/null
nvim "+silent call dein#install()" +UpdateRemotePlugins +qall > /dev/null
