#!/bin/bash

cd "$(dirname "${BASH_SOURCE}")";

mkdir -p "$HOME/.kube/plugins/"

chmod +x kubectl-*

rsync --exclude ".DS_Store" \
	--exclude ".git" \
	--exclude "init" \
	--exclude "README.md" \
	-avh --no-perms . "$HOME/.kube/plugins";
