#!/bin/bash
#
# Ref: https://github.com/jordanwilson230/kubectl-plugins

pod=$1


i=0
nodes=($(kubectl get pod  -lapp=${pod} -o json | jq -r '.items[] | .spec.nodeName'))
[[ "${nodes[@]}" ]] && label='app'

if [[ -z "${nodes[@]}" ]] ; then
	nodes=($(kubectl get pod  -lcomponent=${pod} -o json | jq -r '.items[] | .spec.nodeName'))
	[[ "${nodes[@]}" ]] && label='component'
fi

if [[ -z "${nodes[@]}" ]] ; then
	nodes=($(kubectl get pod  -lname=${pod} -o json | jq -r '.items[] | .spec.nodeName'))
	[[ "${nodes[@]}" ]] && label='name'
fi

if [[ -z "${nodes[@]}" ]] ; then
	nodes=($(kubectl get pod  -lrun=${pod} -o json | jq -r '.items[] | .spec.nodeName'))
	[[ "${nodes[@]}" ]] && label='run'
fi


[[ -z "${nodes[@]}" ]] && echo -e "\nNo match while searching through labels: app, name, run, or component for $1\n" && exit 1

pods=($(kubectl get pod  -l${label}=${pod} -o json | jq -r '.items[] | .spec.hostname | .metadata.name '))

clear
echo -e "\n__________________________________________________________________________________________ \n|      POD       |             LOCATION             |       NODE IP      |     POD_IP     |"
echo -e "|------------------------------------------------------------------------------------------"
count=0
for node in ${!nodes[@]}; do
	node_ip=$(kubectl get node ${nodes[$node]}  -o json | jq -r '.status.addresses' | jq -r '.[] | select(.type=="ExternalIP").address')

	if [[ -z "$node_ip" ]]; then
		node_ip=$(kubectl get node ${nodes[$node]}  -o json | jq -r '.status.addresses' | jq -r '.[] | select(.type=="InternalIP").address')
	fi

	pod_ip=$(kubectl get po -l${label}=$1 -o json | jq -r '.items['$i'].status.podIP')

	echo -e "|  ${pods[$node]}     ${nodes[$node]}      $node_ip    $pod_ip"
	let i=i+1
done
echo -e "|__________________________________________________________________________________________\n"
