#!/usr/bin/env bash

PY2_VER=2.7.15
PY3_VER=3.7.1

cd "$(dirname "${BASH_SOURCE}")";

sh ./fix-mojave
sh ./fix-pyenv $PY2_VER zlib
sh ./fix-pyenv $PY3_VER zlib sqlite

pyenv global $PY3_VER

git clone https://github.com/pyenv/pyenv-virtualenv.git $(pyenv root)/plugins/pyenv-virtualenv
