#!/bin/bash

eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

pyenv virtualenv ${PY2_VER:-2.7.15} neovim2
pyenv virtualenv ${PY3_VER:-3.7.1} neovim3

pyenv activate neovim2
pip install neovim

pyenv activate neovim3
pip install neovim

pip install flake8
# ln -s `pyenv which flake8` ~/bin/flake8  # Assumes that $HOME/bin is in $PATH
